version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python hello.py"
    environment:
      - DB_HOST=db
      - DB_NAME=regions
      - DB_USER=mongo
      - DB_PASS=mongo123
    depends_on:
      - db

  db:
    image: mongo
    container_name: "my-mongo-container"
    environment:
      - MONGO_INITDB_ROOT_DATABASE=regions
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    ports:
      - "27017-27019:27017-27019"
